### ISSUE TITLE
Add new items to the shopcart

### ISSUE THREAD

**Issue by Yuhao-Fan** [2022-DevOps-Shopcarts/shopcarts#2]
**As a User**
**I need to add new items to the shopcart**
**So that I can purchase or check them in the shopcart**

**Details & Assumptions:**

- require product id, product name, and quantity, so that I can add multiple same products into shopcart at the same time
- When I add a product already in shopcart, these two items should be merged into one, which means the quantity should be increased on the previous basis

**Acceptance Criteria:**
```
When I add products into shopcart
Then I should get an "Added successfully" return message.
```

**Comment by zqf0722** [comment]
Close this issue. The function of this issue is addressed in #4.
